channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pango>=1.42.0
  - pandas>=1.3.2
  - psycopg2
  - open-fonts
  - xorg-libxrender
  - xorg-libxext
  - xorg-libxau
  - pip:
    - '-r requirements.txt'
