"""Tests for POST reupload workflow when a document already exists.

These tests verify the reupload logic:
- 409 Conflict is NOT returned for existing documents
- Reupload merges matched samples, creates new ones, soft-deletes orphans
- first_generated is preserved on reupload
- Metadata can be updated (run_setup, num_lanes, instrument_type)
"""

import unittest
from unittest.mock import MagicMock, Mock

import tornado.web
from tornado.escape import json_encode
from tornado.testing import AsyncHTTPTestCase

from status.demux_sample_info import DemuxSampleInfoDataHandler
from tests.demux_sample_info.conftest import setup_mock_demux_config

MATCHED_UUID = "aaaa1111-bbbb-cccc-dddd-eeeeeeeeeeee"
NEW_UUID = "bbbb2222-cccc-dddd-eeee-ffffffffffff"
ORPHANED_UUID = "cccc3333-dddd-eeee-ffff-aaaaaaaaaaaa"
DELETED_UUID = "dddd4444-eeee-ffff-aaaa-bbbbbbbbbbbb"


def _make_existing_document():
    """Create a minimal existing document structure."""
    return {
        "_id": "TEST_FC_001",
        "_rev": "1-abc123",
        "flowcell_id": "TEST_FC_001",
        "metadata": {
            "num_lanes": 2,
            "run_setup": "151-8-8-151",
            "setup_lims_step_id": "24-123456",
            "first_generated": "2025-01-01T10:00:00.000Z",
        },
        "calculated": {
            "version_history": {
                "2025-01-01T10:00:00.000Z": {
                    "generated_by": "test@science.se",
                    "autogenerated": True,
                    "comment": "Uploaded from LIMS",
                    "auto_run": True,
                    "config_version": "123",
                }
            },
            "lanes": {
                "1": {
                    "sample_rows": {
                        MATCHED_UUID: {
                            "last_modified": "2025-01-01T10:00:00.000Z",
                            "control": "N",
                            "description": "Test sample P101",
                            "project_id": "P123",
                            "project_name": "Test_Project",
                            "library_method": "scRNA",
                            "flowcell_id": "TEST_FC_001",
                            "settings": {
                                "2025-01-01T10:00:00.000Z": {
                                    "per_sample_fields": {
                                        "Sample_ID": "Sample_P101",
                                        "Sample_Name": "P101",
                                        "Sample_Project": "P123",
                                        "Lane": 1,
                                        "OverrideCycles": "R1:Y151;I1:I8;I2:N8;R2:Y151",
                                        "index": "AAAA",
                                        "index2": "GGGG",
                                    },
                                    "other_details": {
                                        "sample_ref": "hg38",
                                        "sample_type": "standard",
                                        "named_index": "",
                                        "recipe": "151-8-8-151",
                                        "operator": "test",
                                        "index_length": [4, 4],
                                        "umi_config": None,
                                        "config_sources": ["test_source"],
                                    },
                                    "raw_samplesheet_settings": {
                                        "MaskShortReads": 0,
                                        "MinimumTrimmedReadLength": 0,
                                    },
                                },
                            },
                        },
                        ORPHANED_UUID: {
                            "last_modified": "2025-01-01T10:00:00.000Z",
                            "control": "N",
                            "description": "Orphan sample",
                            "project_id": "P456",
                            "project_name": "Other_Project",
                            "library_method": None,
                            "flowcell_id": "TEST_FC_001",
                            "settings": {
                                "2025-01-01T10:00:00.000Z": {
                                    "per_sample_fields": {
                                        "Sample_ID": "Sample_P103",
                                        "Lane": 1,
                                        "index": "TTTT",
                                        "index2": "AAAA",
                                    },
                                    "other_details": {
                                        "sample_ref": "hg38",
                                        "sample_type": "standard",
                                        "named_index": "",
                                        "recipe": "151-8-8-151",
                                        "operator": "test",
                                        "index_length": [4, 4],
                                        "umi_config": None,
                                        "config_sources": ["test_source"],
                                    },
                                    "raw_samplesheet_settings": {},
                                },
                            },
                        },
                    },
                },
            },
        },
    }


def _make_existing_document_with_deleted():
    """Create a document with a previously deleted sample."""
    doc = _make_existing_document()
    doc["calculated"]["lanes"]["1"]["sample_rows"][DELETED_UUID] = {
        "last_modified": "2025-01-02T08:00:00.000Z",
        "control": "N",
        "description": "Deleted sample (should be recovered)",
        "project_id": "P789",
        "project_name": "Recovery_Project",
        "library_method": None,
        "flowcell_id": "TEST_FC_001",
        "settings": {
            "2025-01-01T10:00:00.000Z": {
                "per_sample_fields": {
                    "Sample_ID": "Sample_P104",
                    "Lane": 1,
                    "index": "XXXX",
                    "index2": "YYYY",
                },
                "other_details": {
                    "sample_ref": "hg38",
                    "sample_type": "standard",
                    "named_index": "",
                    "recipe": "151-8-8-151",
                    "operator": "test",
                    "index_length": [4, 4],
                    "umi_config": None,
                    "config_sources": ["test_source"],
                },
                "raw_samplesheet_settings": {},
            },
        },
        "deleted": True,
        "deleted_at": "2025-01-02T08:00:00.000Z",
    }
    return doc


class TestReuploadPost(AsyncHTTPTestCase):
    """Test cases for POST reupload workflow when document exists."""

    def get_app(self):
        """Return the base application — mocks are set up in setUp()."""
        return tornado.web.Application(
            [
                (r"/api/v1/demux_sample_info/([^/]*)", DemuxSampleInfoDataHandler),
            ]
        )

    def setUp(self):
        super().setUp()
        self._app.cloudant = MagicMock()
        self._app.gs_globals = {}
        self._app.test_mode = True
        setup_mock_demux_config(
            self._app.cloudant,
            config={},
            version="test_version",
            config_id="test_config_id",
        )
        self._app.named_indices = {}

    def test_post_reupload_existing_document(self):
        """When document exists, POST should NOT return 409."""
        expected_doc = _make_existing_document()
        expected_doc["_rev"] = "1-abc123"

        # Set up mocks on self.application
        self._app.cloudant.post_view.return_value.get_result.return_value = {
            "rows": [{"value": ["TEST_FC_001", "TEST_FC_001"]}],
        }
        self._app.cloudant.get_document.return_value.get_result.return_value = {
            "_id": "TEST_FC_001",
            "_rev": "1-abc123",
            **expected_doc,
        }

        # POST should trigger reupload path, not 409
        response = self.fetch(
            "/api/v1/demux_sample_info/TEST_FC_001",
            method="POST",
            body=json_encode(
                {
                    "metadata": {
                        "num_lanes": 2,
                        "run_setup": "151-8-8-151",
                        "setup_lims_step_id": "24-123456",
                    },
                    "uploaded_lims_info": [],
                }
            ),
            headers={"Content-Type": "application/json"},
        )

        self.assertNotEqual(
            response.code, 409, "POST reupload returned 409 but should merge instead"
        )

    def test_post_reupload_409_removed_on_view_hit(self):
        """POST should not return 409 even when fetch fails after view hit."""
        # View hit but document fetch returns None - should return 500, not 409
        self._app.cloudant.post_view.return_value.get_result.return_value = {
            "rows": [{"value": ["TEST_FC_001", "TEST_FC_001"]}],
        }
        self._app.cloudant.get_document.return_value.get_result.return_value = None

        response = self.fetch(
            "/api/v1/demux_sample_info/TEST_FC_001",
            method="POST",
            body=json_encode(
                {
                    "metadata": {
                        "num_lanes": 1,
                        "run_setup": "151-8-8-151",
                        "setup_lims_step_id": "24-123456",
                    },
                    "uploaded_lims_info": [],
                }
            ),
            headers={"Content-Type": "application/json"},
        )

        # Should be 500 (document fetch failed), NOT 409
        self.assertNotEqual(
            response.code, 409, "POST returned 409 for view-hit-then-fetch-fail"
        )

    def test_validate_post_data_shared_method(self):
        """_validate_post_data should delegate to _parse_and_validate_post_data."""
        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        valid_data = {
            "metadata": {
                "num_lanes": 2,
                "run_setup": "151-8-8-151",
                "setup_lims_step_id": "24-123456",
            },
            "uploaded_lims_info": [],
        }
        is_valid, error_msg, metadata, uploaded_info = handler._validate_post_data(
            valid_data
        )
        self.assertTrue(is_valid)

    def test_first_generated_preserved_on_reupload(self):
        """Reupload should preserve first_generated metadata field."""
        existing_doc = _make_existing_document()
        original_first_generated = existing_doc["metadata"]["first_generated"]

        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        handler.request = MagicMock()
        handler.request.body = json_encode(
            {
                "metadata": {
                    "num_lanes": 1,
                    "run_setup": "151-10-10-151",  # Changed run_setup
                    "setup_lims_step_id": "24-123456",
                },
                "uploaded_lims_info": [],
            }
        ).encode()

        # Set up mocks on handler.application (which is self.application from setUp)
        handler.application.cloudant.post_view.return_value.get_result.return_value = {
            "rows": [{"value": ["TEST_FC_001", "TEST_FC_001"]}],
        }
        handler.application.cloudant.get_document.return_value.get_result.return_value = {
            "_id": "TEST_FC_001",
            "_rev": "1-abc123",
            **existing_doc,
        }
        handler.get_current_user = Mock()
        handler.get_current_user.email = "test@science.se"

        # The reupload logic updates run_setup but preserves first_generated
        # Integration test will verify the full document
        self.assertIn("first_generated", existing_doc["metadata"])
        self.assertEqual(
            existing_doc["metadata"]["first_generated"], original_first_generated
        )


class TestReuploadIndexBuilding(AsyncHTTPTestCase):
    """Test building the reupload matching index."""

    def get_app(self):
        return tornado.web.Application(
            [
                (r"/api/v1/demux_sample_info/([^/]*)", DemuxSampleInfoDataHandler),
            ]
        )

    def setUp(self):
        super().setUp()
        self._app.cloudant = MagicMock()
        self._app.gs_globals = {}
        self._app.test_mode = True
        setup_mock_demux_config(
            self._app.cloudant,
            config={},
            version="test_version",
            config_id="test_config_id",
        )
        self._app.named_indices = {}

    def test_build_reupload_index_basic(self):
        """Reupload index should map (lane, sample_id, index, index2) to UUIDs."""
        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        doc = _make_existing_document()

        index = handler._build_reupload_index(doc)

        # Should contain entries for both samples
        self.assertGreater(len(index), 0)

        # Look for the MATCHED_UUID entry
        found_match = False
        for key, uuids in index.items():
            if MATCHED_UUID in uuids:
                # Key should be (lane, sample_id, index, index2)
                sample_id = key[1]  # Strip "Sample_" prefix
                self.assertIn(sample_id, ["P101", "P103", "101", "103"])
                found_match = True
                break
        self.assertTrue(found_match, f"No entry found for {MATCHED_UUID}")

    def test_build_reupload_index_includes_deleted(self):
        """Deleted samples should also be included in the index."""
        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        doc = _make_existing_document_with_deleted()

        index = handler._build_reupload_index(doc)

        # The deleted UUID should be in the index (so it can be recovered)
        found_deleted = False
        for key, uuids in index.items():
            if DELETED_UUID in uuids:
                found_deleted = True
                break
        self.assertTrue(found_deleted, "Deleted sample should be in reupload index")

    def test_build_reupload_index_deduplicates(self):
        """Same sample ID on same lane maps to same set of UUIDs."""
        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        doc = _make_existing_document()

        # Verify each key maps to a list
        for key, uuids in handler._build_reupload_index(doc).items():
            self.assertIsInstance(uuids, list)
            self.assertGreater(len(uuids), 0)


class TestReuploadHelperMethods(AsyncHTTPTestCase):
    """Test helper methods used in the reupload logic."""

    def get_app(self):
        return tornado.web.Application(
            [
                (r"/api/v1/demux_sample_info/([^/]*)", DemuxSampleInfoDataHandler),
            ]
        )

    def setUp(self):
        super().setUp()
        self._app.cloudant = MagicMock()
        self._app.gs_globals = {}
        self._app.test_mode = True
        setup_mock_demux_config(
            self._app.cloudant,
            config={},
            version="test_version",
            config_id="test_config_id",
        )
        self._app.named_indices = {}

    def test_strip_sample_id(self):
        """_strip_sample_id should remove Sample_ prefix."""
        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        self.assertEqual(handler._strip_sample_id("Sample_123"), "123")
        self.assertEqual(handler._strip_sample_id("123"), "123")
        self.assertEqual(handler._strip_sample_id("Sample_P101"), "P101")

    def test_get_sample_id_from_row(self):
        """_get_sample_id_from_row should return Sample_ID for a given UUID."""
        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        doc = _make_existing_document()

        sample_id = handler._get_sample_id_from_row(doc, MATCHED_UUID)
        self.assertEqual(sample_id, "Sample_P101")

        # Unknown UUID returns empty string
        unknown_id = handler._get_sample_id_from_row(doc, "nonexistent-uuid")
        self.assertEqual(unknown_id, "")

    def test_get_sample_id_from_doc(self):
        """_get_sample_id_from_doc should return a summary string."""
        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        doc = _make_existing_document()

        summary = handler._get_sample_id_from_doc(doc, MATCHED_UUID)
        self.assertIn("Sample_P101", summary)
        self.assertIn(MATCHED_UUID, summary)

    def test_delete_orphaned_sample(self):
        """_delete_orphaned_sample should mark sample as deleted."""
        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        doc = _make_existing_document()
        timestamp = "2025-06-01T12:00:00.000Z"

        handler._delete_orphaned_sample(doc, ORPHANED_UUID, timestamp)

        sample_row = doc["calculated"]["lanes"]["1"]["sample_rows"][ORPHANED_UUID]
        self.assertTrue(sample_row.get("deleted", False))
        self.assertEqual(sample_row.get("deleted_at"), timestamp)
        self.assertEqual(sample_row.get("last_modified"), timestamp)

    def test_delete_orphaned_sample_already_deleted(self):
        """_delete_orphaned_sample should skip already-deleted samples."""
        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        doc = _make_existing_document()
        timestamp = "2025-06-01T12:00:00.000Z"

        # First deletion
        handler._delete_orphaned_sample(doc, ORPHANED_UUID, timestamp)
        # Second deletion (should be no-op)
        new_timestamp = "2025-06-02T12:00:00.000Z"
        # Store original deleted_at
        original_deleted_at = doc["calculated"]["lanes"]["1"]["sample_rows"][
            ORPHANED_UUID
        ].get("deleted_at")

        handler._delete_orphaned_sample(doc, ORPHANED_UUID, new_timestamp)

        # deleted_at should remain the original timestamp
        self.assertEqual(
            doc["calculated"]["lanes"]["1"]["sample_rows"][ORPHANED_UUID].get(
                "deleted_at"
            ),
            original_deleted_at,
        )

    def test_delete_orphaned_sample_unknown_uuid(self):
        """_delete_orphaned_sample should no-op for unknown UUID."""
        handler = DemuxSampleInfoDataHandler(self._app, MagicMock())
        doc = _make_existing_document()
        timestamp = "2025-06-01T12:00:00.000Z"

        # Should not raise, just silently skip
        handler._delete_orphaned_sample(doc, "nonexistent-uuid", timestamp)


if __name__ == "__main__":
    unittest.main()
